### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by MetaMmodern** [peterarsentev/course_test#4]
У вас опечатка в ридми. 
Задача 21: Задач вместо Задан

**Comment by peterarsentev** [comment]
@MetaMmodern Можете сделать pull request c правками?

**Comment by MetaMmodern** [comment]
> @MetaMmodern Можете сделать pull request c правками?

Могу)

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
